### ISSUE TITLE
Get a checksum error in Repetier

### ISSUE THREAD

**Issue by ghost** [dattas/OctoPrint-DetailedProgress#1]
Some of the log: http://pastebin.com/HxniEJks

Running Repetier 0.92.4, Octoprint 1.2.15

**Comment by dattas** [comment]
@sworah you can change the text of what gets sent (see the readme), repetier firmware doesn't act like most others and the m117 commands are fine. I won't be doing any firmware detecting to try to handle this in the plugin, sorry.
