### ISSUE TITLE
No ETA/ETL yet ?

### ISSUE THREAD

**Issue by Sebclem** [dattas/OctoPrint-DetailedProgress#12]
Hy!

Today, when i launch a print, my screen show "no ETA/ETL yet".... 
Percentage work well, that very strange :/

PS: Sorry for my bad english, i'm French ;)

**Comment by dattas** [comment]
This only shows when Octoprint doesn't have an ETA yet. Once Octoprint's UI gives you an ETA, it will display on your printer's LCD as well.
