### ISSUE TITLE
Broken with 1.3.7rc1

### ISSUE THREAD

**Issue by b-morgan** [dattas/OctoPrint-DetailedProgress#26]
I upgraded OctoPrint to 1.3.7rc1 and I'm not seeing the status messages.

**Comment by b-morgan** [comment]
It was suggested that I add these log files (although I don't see anything useful).

[Temp.zip](https://github.com/dattas/OctoPrint-DetailedProgress/files/1830772/Temp.zip)

**Comment by foosel** [comment]
Will be fixed by 1.3.7rc2. But helped me to discover that this plugin's (unintentionally) modification of the global `progress` dictionary was probably the reason for a concurrent modification issue I've been hunting for many many moons now, so yay! :relaxed:
