### ISSUE TITLE
Does not work for Anycubic i3 Mega printer

### ISSUE THREAD

**Issue by fr2632** [dattas/OctoPrint-DetailedProgress#27]
![img_20180415_131920](https://user-images.githubusercontent.com/38398270/38777963-6b2956de-40b1-11e8-823d-daef4a0e9232.jpg)

**Comment by otherguy** [comment]
Nothing the plugin author can do about that. The Anycubic i3 Mega does not support `M117` commands. You can switch to Marlin if you have an 8 bit board though.
