### ISSUE TITLE
Messages are queued when printer is busy

### ISSUE THREAD

**Issue by tcm0116** [dattas/OctoPrint-DetailedProgress#30]
If the printer is busy (i.e. during a filament change), this plugin will continue to generate messages. These messages end up being queued, and when the printer is no longer busy, the queue has to be drained before printing can resume. This isn't too much of an issue for short pauses, but it can be a bigger issue if the print is paused for several hours, which will result in the printer rapidly displaying these queued messages for 10 of seconds until they are caught up.

My recommendation would be to suspend the generation of the messages while the printer is busy or waiting.

**Comment by Patronics** [comment]
I've had the same issue, it's very annoying to wait for a few minutes for the printer to catch up, and it effectively caused a few failed prints before I realized the cause of the issue, it looks like the printer is glitching out and nonfunctional (Sitting still, fan whiring, screen mostly blank and slightly pulsing), so I would hit the reset button.
