### ISSUE TITLE
IP is cut off on the LCD

### ISSUE THREAD

**Issue by tronicgr** [dattas/OctoPrint-DetailedProgress#4]
The IP on my network is longer than the allowed characters length on the LCD display (Duplicator i3) and cuts the last number out. 

The IP range on my network is in 10.255.255.255

Perhaps you can change it to display the number without the "IP is: ..."

Thanks
Thanos

**Comment by 1n5aN1aC** [comment]
Perhaps just IP:

That way, you get the idea, while being 3 characters shorter.
