### ISSUE TITLE
missing parameters in config.yaml

### ISSUE THREAD

**Issue by jon-daemon** [dattas/OctoPrint-DetailedProgress#41]
I cannot find the configuration parameters in config.yaml file.
Is this plkugin supported on the latest version of Octoprint?

**Comment by PhilKloppers** [comment]
After initial installation, the relevant section is missing in config.yaml, but adding the lines manually works just fine, and you can customise as needed from there.

A restart of OctoPrint is needed after each change, and confirm that the changes stick after the restart as I've had it revert to pre-restart settings several times.
