### ISSUE TITLE
Features to disable the switching to ETA and ETL

### ISSUE THREAD

**Issue by mjparme** [dattas/OctoPrint-DetailedProgress#44]
It would be nice if there was a way to keep the plugin from switching to ETA and ETL. I found these numbers to be widely inaccurate and even if they were accurate they don't give me much value.

I would love if the display would just always show `[progress]% L=[current_layer]/[total_layers]`.

Could an option be added to remove the switching to ETA and ETL?

**Comment by tremrej** [comment]
This feature already exist. You have to modify the config file. On Linux, this file is .octoprint/config.yaml. Personnalty I only kept % complete and ETL. Here's my config:
plugin:
    detailedprogress:
        eta_strftime: '%H:%M:%S Day %d'
        etl_format: '{hours:02d}:{minutes:02d}:{seconds:02d}'
        messages:
        - '{completion:.2f}% complete'
        - 'ETL: {printTimeLeft}'
        time_to_change: 5
