### ISSUE TITLE
Output to LCD 

### ISSUE THREAD

**Issue by azalanono** [dattas/OctoPrint-DetailedProgress#8]
I installed the DetailedProgress plugin and find it very helpful. 

My 3D printer uses Marlin Firmware and has a 20x4 LCD installed. Everything is fine, but I noticed that  following things need either explanation or correction:

- The LCD displays an ETA being far away from reality.  I started a printjob with ~45 minutes running time and see an ETA of some days(!)  This is absolutely wrong. When ETA calculation is a problem, it should be better removed.  It would be more helpful to see the IP address instead.

- The format of ETA is very unusual. I would recommend something like this: "DD.HH:MM:SS"

- ETL is displaying a correct value, but I would suggest the same format here, too.  "DD.HH:MM:SS"

- The detailed done percentage has a funny output:  "99.9p .....".  Why not use the "%" sign, it definitely works with M117 command? 

- Displaying the IP address periodically would be a nice additional output. At the moment, the IP is only shows when the printer is idle.

It would be the best to extend the plugin by a settings editor. 
This will allow to turn particular messages on/off as needed. In this editor it should also be possible to enter the format string to be used.

**Comment by cosmith71** [comment]
I agree with this.  I'm a noobie...is there a way to configure the way the messages are displayed?

Thanks,

--Colin

**Comment by cosmith71** [comment]
OK, somehow got the configuration to work.  I put the sample config on the front page into config.yaml.  Something then modified it and took out all the comments and set the cycle time to NULL.  I was able to modify the new, mystery configuration to my liking.  I'm not really sure what happened, but it's working now.  I have a % instead of the 'p'.  I think there may be something flaky with the way it sets up its configuration.

**Comment by jasoncross** [comment]
I'm trying to do the same, but can't find where I update the configuration.  Can you point me in the right direction?

**Comment by mkotek** [comment]
I have the same issue as cosmith71, also saving the defaults has caused the comments to be removed, but the configuration using % as suggested in readme does not work in my case - I am getting errors (as seen in terminal). I am trying to see, if the amended formatting written in the init file directly will be showing up correctly.
Any ideas, why the standard config works from init file, but the same entries as defaults in config.yaml do not?

Update 2017/05/03:
As promised, I have run the check by modyfing the __init__.py script directly.
Here are my findings (please note, most errors result from us using 4x20 text display and not the graphical one.
If I set the % sign next to the completion: {completion:.2f}% complete, the result is 7.86omplete on LCD and correct 7.86 complete on Status Line plugin in OctoPrint.
If I set eta_strftime = "%H:%M:%S D:%d", the result on LCD is just an hour, ie. ETA 17, rest is blank, but the Status Line shows correct result: ETA 17:12:12 D:06 as expected
If I leave etl_format as is, it is being displayed with 01h12m00s as expected in both places.

Can you think of the way to correct the display on text LCD?

Update 2017/05/08:
The proposed defaults do not work for me in text LCD.
I have settled on "{completion:.2f}%   complete" (three spaces) and "%Hh%Mm D %d" respectively and it works ok in Status Line plugin and on my LCD screen (although % is not displayed). Mind you, I have tried escaped % as %%, but this did not work in my case (Anet A8, original firmware, text LCD).

**Comment by dipusone** [comment]
Thanks @mkotek this settings saved me!

**Comment by christhesmith** [comment]
@mkotek In playing around with this plugin over the last few days, I discovered that for my Maker Select v2.1 running Repetier, I was able to get the percent sign to display by using three '%' symbols in the config like so:

'{completion:.2f}%%% complete'

That said, with this printer/firmware, it appears that the colon ':' cannot be displayed in the same way (perhaps interpreted as a comment, like the semicolon?), so I changed the formats for the other two messages to what's below, and they seem to work properly now:
