### ISSUE TITLE
a real correct calculation including jerk and acceleration

### ISSUE THREAD

**Issue by TylonHH** [dattas/OctoPrint-DetailedProgress#9]
Hi,
because I love to have the control and a overview of an print I realy like your plugin. So I wanna give you a suggestion to boost the calculation precision. May it's useful for you too.

Here is actual what I'm using.
From this project: https://github.com/davr/Marlin/tree/estimate/Marlin I use an estimate time calculator mentioned and explained [here](http://www.3d-druck-community.de/thread-15074-post-93461.html)(german)
It hits the time on the minute. So maybe you can use this calcutaion for this (or an new) plugin too.

Maybe you can have a look.

If you need information how I use this, let me know.

cheers

**Comment by dattas** [comment]
We simply use the estimates coming from Octoprint. I'm not interested in writing calculations for this job. I would recommend you open a ticket for octoprint if you want this type of calculations to happen.
